[package]
name = "beastie-view"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
beastie-core = { path = "../beastie-core" }
serde.workspace = true
rustybuzz = "0.20"
unicode-segmentation = "1.12"

[dev-dependencies]
serde_json.workspace = true
